config/routes.rb
CES::Application.routes.draw do
  resources :rooms


  resources :categories


  resources :events

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}


  authenticated :user do
    root :to => 'events#index'
  end
  root :to => "events#index"
  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  resources :users

  #, :only => [:show, :index]
end

app/models/event.rb
class Event < ActiveRecord::Base
  attr_accessible :body, :start_at, :end_at, :music, :room_id, :scripture, :title, :category_ids, :user_id
  validates_presence_of :title, :body, :start_at, :end_at, :room_id ,:user_id, :categories
  belongs_to :user
  has_and_belongs_to_many :categories
  belongs_to :room
  has_event_calendar


  validate :start_before_end
  validate :uniqueness_of_date_range

  scope :published, lambda {where(['end_at <= ?', Date.today])}
  scope :by_user_id, lambda {|uid| where(:user_id => uid)}
  scope :by_category_id, lambda {|cid| joins(:categories).where(['categories.id =?',cid])}
  scope :past_event, lambda {where(['start_at >= ?', Date.today])}
end

def start_before_end
  if end_at <= start_at
    errors.add(:start_at, 'has to be before the end date')
    if start_at >= end_at
      errors.add(:start_at, 'has to be before the end date')

    end
  end

  def start_must_be_in_future

    if Date.today >= start_at
    errors.add(:start_at, "Date cannot be in past.")

    end
  end

  def uniqueness_of_date_range

    errors.add(:room_id, "Room is reserved. Please choose a different room.") unless Event.where("? == room_id AND ? >= start_at AND ? <= end_at", room_id, start_at, end_at).count == 0
    errors.add(:room_id, "Room is reserved. Please choose a different room.") unless Event.where("? == room_id AND ? >= start_at AND ? <= end_at", room_id, end_at, end_at).count == 0

  end

  def reserved
    @Event.new[:room_id]

  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  # GET /events
  # GET /events.json
  def index
    @events = Event.order('start_at ASC').where('start_at > ?', Date.today)
    @events = @events.by_user_id(params[:user]) if params[:user].present?
    @events = @events.by_category_id(params[:cat]) if params[:cat].present?

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @events }
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @event = Event.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/new
  # GET /events/new.json
  def new
    @event = Event.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @event }
    end
  end

  # GET /events/1/edit
  def edit
    @event = Event.find(params[:id])
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(params[:event])
    @event.user_id = current_user.id

      respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render json: @event, status: :created, location: @event }
      else
        format.html { render action: "new" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /events/1
  # PUT /events/1.json
  def update
    @event = Event.find(params[:id])

    respond_to do |format|
      if @event.update_attributes(params[:event])
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event = Event.find(params[:id])
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for @event, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.error_notification %>
  <%= f.input :title %>
  <%= f.association :categories, label_method: :eventType,:as => :check_boxes %>
  <%= f.input :body %>
  <%= f.input :start_at, :as => :datetime_picker%>
  <%= f.input :end_at, :as => :datetime_picker%>
  <%= f.input :room_id do %>
  <%= f.collection_select :room_id, Room.all, :id, :name, :prompt => "Select Room" %> <% end %>
  <%= f.input :music %>
  <%= f.input :scripture %>
  <div class="form-actions">
    <%= f.button :submit, :class => 'btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                events_path, :class => 'btn' %>
  </div>
<% end %>

app/views/events/edit.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/index.html.erb
<% @events.each do |event| %>
    <div class="row">
      <div class="span8"><h2><%= link_to event.title, event_path(event)  %> </h2></div>
      <div class="span4"><h3><%= l event.start_at, :format => :long %></h3></div>
    </div>
    <div class="row">
      <div class="span8">Pastor: <%= link_to event.user.name, root_path(:user => event.user.id) %></div>
      <div class="span4">Categories:
        <% event.categories.each do |cat| %>
            <%= link_to cat.eventType, root_path(:cat => cat.id) %>
        <% end %>
      </div>
    </div>
    <br/>
    <blockquote><%= event.body %></blockquote>

    <% if current_user && (current_user.has_role?(:admin) || current_user.id==event.user_id) %>
        <%= link_to t('.edit', :default => t("helpers.links.edit")),
                    edit_event_path(event), :class => 'btn btn-mini' %>
        <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                    event_path(event),
                    :method => :delete,
                    :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                    :class => 'btn btn-mini btn-danger' %>

    <% end %>
    <hr />
<% end %>

<% if current_user %>
    <%= link_to t('.new', :default => t("helpers.links.new")),
            new_event_path,
            :class => 'btn btn-primary' %>
<% end %>

app/views/events/new.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/events/show.html.erb
<%- model_class = Event -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @event.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:body) %>:</strong></dt>
  <dd><%= @event.body %></dd>
  <dt><strong><%= model_class.human_attribute_name(:start_at) %>:</strong></dt>
  <dd><%= @event.start_at%></dd>
  <dt><strong><%= model_class.human_attribute_name(:end_at) %>:</strong></dt>
  <dd><%= @event.end_at%></dd>
  <dt><strong><%= model_class.human_attribute_name(:room_id) %>:</strong></dt>
  <dd><%= @event.room.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:music) %>:</strong></dt>
  <dd><%= @event.music %></dd>
  <dt><strong><%= model_class.human_attribute_name(:scripture) %>:</strong></dt>
  <dd><%= @event.scripture %></dd>
  <dt><strong><%= model_class.human_attribute_name(:user_id) %>:</strong></dt>
  <dd><%= @event.user.name %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              events_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_event_path(@event), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              event_path(@event),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>