config/routes.rb
CES::Application.routes.draw do
  resources :rooms


  resources :categories


  resources :events

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}


  authenticated :user do
    root :to => 'events#index'
  end
  root :to => "events#index"
  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  resources :users

  #, :only => [:show, :index]
end

app/models/room.rb
class Room < ActiveRecord::Base
  attr_accessible :name, :id
  has_and_belongs_to_many :events
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rooms }
    end
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
    @room = Room.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/new
  # GET /rooms/new.json
  def new
    @room = Room.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @room }
    end
  end

  # GET /rooms/1/edit
  def edit
    @room = Room.find(params[:id])
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(params[:room])

    respond_to do |format|
      if @room.save
        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render json: @room, status: :created, location: @room }
      else
        format.html { render action: "new" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /rooms/1
  # PUT /rooms/1.json
  def update
    @room = Room.find(params[:id])

    respond_to do |format|
      if @room.update_attributes(params[:room])
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    @room = Room.find(params[:id])
    @room.destroy

    respond_to do |format|
      format.html { redirect_to rooms_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= simple_form_for(@room) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing room</h1>

<%= render 'form' %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<h1>Listing rooms</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rooms.each do |room| %>
  <tr>
    <td><%= room.name %></td>
    <td><%= link_to 'Show', room %></td>
    <td><%= link_to 'Edit', edit_room_path(room) %></td>
    <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>

<%= render 'form' %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @room.name %>
</p>


<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>