config/routes.rb
CES::Application.routes.draw do
  resources :rooms


  resources :categories


  resources :events

  match '/calendar(/:year(/:month))' => 'calendar#index', :as => :calendar, :constraints => {:year => /\d{4}/, :month => /\d{1,2}/}


  authenticated :user do
    root :to => 'events#index'
  end
  root :to => "events#index"
  devise_for :users,  :controllers => { :registrations => "users/registrations" }
  resources :users

  #, :only => [:show, :index]
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 2.3 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&times;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 2.3 %>
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="nav-collapse collapse">
        <div class="navbar navbar-fixed-top">
          <nav class="navbar-inner">
            <ul class="nav">
              <li><%= link_to 'Home', root_path %><li>
              <li><%= link_to 'Event Calendar', calendar_path %></li>
              <%= render 'layouts/navigation_links' %>
            </ul>
          </nav>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<% if user_signed_in? %>

  <li><%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Login', new_user_session_path %></li>
<% end %>
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <% if current_user.has_role? :admin %>
  <li><%= link_to 'Users', users_path %></li>
  <li><%= link_to 'Events', events_path %></li>
  <li><%= link_to 'Categories', categories_path %></li>
  <li><%= link_to 'Rooms', rooms_path %></li>


<% end %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CES" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "CES" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  </head>
  <body>
    <%# application layout styled for Bootstrap 2.3 %>
    <header>
      <%= render 'layouts/navigation' %>
      <img src="<%= asset_path( 'logo.png' ) %>"/>

    </header>
    <main role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div>
    </main>
  </body>
</html>